version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.22.1'
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      # - run: dockerize -wait http://127.0.0.1:4000 -timeout 10s
      - run: sleep 5

    - run: echo 127.0.0.1 devhost | sudo tee -a /etc/hosts

      - run: |
      sudo -u root createuser -h localhost --superuser ubuntu &&
      sudo createdb -h localhost test_db
      - run: ps aux
      - run: npm run test

