version: 2.1
orbs:
  node: circleci/node@1.1
jobs:
  build:
    executor:
      name: node/default
      tag: '10.22.1'
    steps:
     - run:
        command: dockerize -wait tcp://127.0.0.1:4000 -timeout 120s
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
      - run: npm run test

